name: adaptive_golden_test
description: A Flutter package to generate adaptive golden files during widget tests.
repository: https://github.com/StorybookToolkit/adaptive_golden_test
issue_tracker: https://github.com/StorybookToolkit/adaptive_golden_test/issues
version: 1.2.0

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.12.0
  package_config: ^2.1.0
  path: ^1.8.2
  platform: ^3.1.0
  recase: ^4.1.0
  device_frame_plus: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
