name: adaptive_golden_test
description: A Flutter package to generate adaptive golden files during widget tests.
repository: https://github.com/mjablecnik/adaptive_golden_test
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.12.0
  path: ^1.8.2
  platform: ^3.1.0
  recase: ^4.1.0
  device_frame_plus: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
